### ISSUE TITLE
Pass stdin to stdout if optimization was not possible

### ISSUE THREAD

**Issue by KrylosovM** [tjko/jpegoptim#50]
```
cat a.jpg | jpegoptim --stdin > b.jpg
```
Would be great if input file from stdin passed to stdout when result of optimization is larger than original.
At the moment `--stdin` option enables `--force` option that forces optimized file to stdout, even if it is larger than original.

**Comment by Lewiscowles1986** [comment]
I Just got this same thing trying to make this into a serverless function.

**Comment by Lewiscowles1986** [comment]
going to try this out with a build. 

* https://github.com/tjko/jpegoptim/blob/master/jpegoptim.c#L468 
  seems to be the place to go to start
* https://github.com/tjko/jpegoptim/blob/master/jpegoptim.c#L469
  could benefit from enforcing quiet for my purposes (otherwise my serverless function outputs noise that outputs an invalid jpeg
* https://github.com/tjko/jpegoptim/blob/master/jpegoptim.c#L808
  Add additional checks (probably borrowed from elsewhere)

**Comment by Lewiscowles1986** [comment]
Right I've a patch for this. It was a bit more of a pain than I first thought, but it now works on my PC and I'm pretty happy

**Comment by Lewiscowles1986** [comment]
@KrylosovM @tjko 
My solution would likely benefit from feedback. I've made a heap of assumptions, but I feel pretty positive about it.

The latest commit adds a command line argument for `--read-bytes` shortcode `-B` which takes the number of bytes passed to stdin. It also checks that is larger than the minimum possible size for a valid JPEG, and detects if the input to stdin is larger than the buffer (defaults to 32MB).

It does change the behaviour so that `-f` is not passed by default and that output is silenced when `--stdin` or `--stdout` arguments are provided.

**Comment by tjko** [comment]
This has now been implemented with commit: 05c3f85aa1330f88f20b86c9d535a72735ed33a1
